# vim: set filetype=tcl :

# build

spawn mlton main.mlb
exitstatus should be 0 or "building failed"

spawn sheeprun.tcl testsuite/fixture/match.shp
expect eof
exitstatus should be 0

spawn sheeprun.tcl testsuite/fixture/function.shp
expect eof
exitstatus should be 0

spawn sheeprun.tcl testsuite/fixture/bang.shp
expect "hello"
expect "hello world"
expect "hello world 2 !"
expect "cheer cheer cheer"
expect "cheer cheer cheer cheer"
expect "( cheer cheer cheer )"
expect "true"
expect "false"
expect "goodbye"
expect "goodbye world !"
expect eof
exitstatus should be 0

spawn sheeprun.tcl testsuite/fixture/return.shp
expect eof
exitstatus should be 0

spawn sheeprun.tcl testsuite/fixture/binop.shp
expect eof
exitstatus should be 0

spawn sheeprun.tcl testsuite/fixture/list.shp
expect eof
exitstatus should be 0

spawn sheeprun.tcl testsuite/fixture/for.shp
expect "start"
expect "1"
expect "2"
expect "3"
expect "end"
expect eof
exitstatus should be 0
