# vim: set filetype=tcl :

spawn sheep testsuite/fixture/match.shp
expect eof
exitstatus should be 0

spawn sheep testsuite/fixture/function.shp
expect eof
exitstatus should be 0

spawn sheep testsuite/fixture/bang.shp
expect "hello"
expect "hello world"
expect "hello world 2 !"
expect "cheer cheer cheer"
expect "cheer cheer cheer cheer"
expect "( cheer cheer cheer )"
expect "true"
expect "false"
expect "goodbye"
expect "goodbye world !"
expect eof
exitstatus should be 0

spawn sheep testsuite/fixture/return.shp
expect eof
exitstatus should be 0

spawn sheep testsuite/fixture/binop.shp
expect eof
exitstatus should be 0

spawn sheep testsuite/fixture/list.shp
expect eof
exitstatus should be 0

spawn sheep testsuite/fixture/for.shp
expect "start"
expect "1"
expect "2"
expect "3"
expect "end"
expect eof
exitstatus should be 0

spawn sheep testsuite/fixture/patbody/numfields.shp testsuite/fixture/patbody/numfields.input
expect "one"
expect "two"
expect "three or more"
expect "three or more"
exitstatus should be 0
